catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("books/", views.BookListView.as_view(), name="books"),
    path("books/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path("authors/", views.AuthorListview.as_view(), name="authors"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),
    path("genres/", views.GenreListView.as_view(), name="genres"),
    path("genre/<int:pk>", views.GenreDetailView.as_view(), name="genre-detail"),
    path("languages/", views.LanguageListView.as_view(), name="languages"),
    path(
        "language/<int:pk>", views.LanguageDetailView.as_view(), name="language-detail"
    ),
    path("bookinstances/", views.BookInstanceListView.as_view(), name="bookinstances"),
    path(
        "bookinstance/<uuid:pk>",
        views.BookInstanceDetailView.as_view(),
        name="bookinstance-detail",
    ),
]

# User configured URLs

urlpatterns += [
    path("mybooks/", views.LoanedBooksByUserListView.as_view(), name="my-borrowed"),
    path("borrowed/", views.LoanedBookAllListView.as_view(), name="all-borrowed"),
]


# Form urlpatterns

urlpatterns += [
    path(
        "book/<uuid:pk>/renew/", views.renew_book_librarian, name="renew-book-librarian"
    ),
]

# Create, Delete, Update URLs
urlpatterns += [
    # Author
    path("author/create/", views.AuthorCreate.as_view(), name="author-create"),
    path("author/<int:pk>/update/", views.AuthorUpdate.as_view(), name="author-update"),
    path("author/<int:pk>/delete/", views.AuthorDelete.as_view(), name="author-delete"),
    # Book
    path("book/create/", views.BookCreate.as_view(), name="book-create"),
    path("book/<int:pk>/update/", views.BookUpdate.as_view(), name="book-update"),
    path("book/<int:pk>/delete/", views.BookDelete.as_view(), name="book-delete"),
    # Genre
    path("genre/create/", views.GenreCreate.as_view(), name="genre-create"),
    path("genre/<int:pk>/update/", views.GenreUpdate.as_view(), name="genre-update"),
    path("genre/<int:pk>/delete/", views.GenreDelete.as_view(), name="genre-delete"),
    # Lanaguage
    path("language/create/", views.LanguageCreate.as_view(), name="language-create"),
    path(
        "language/<int:pk>/update/",
        views.LanguageUpdate.as_view(),
        name="language-update",
    ),
    path(
        "language/<int:pk>/delete/",
        views.LanguageDelete.as_view(),
        name="language-delete",
    ),
    # BookInstances
    path(
        "bookinstance/create/",
        views.BookInstanceCreate.as_view(),
        name="bookinstance-create",
    ),
    path(
        "bookinstance/<uuid:pk>/update/",
        views.BookInstanceUpdate.as_view(),
        name="bookinstance-update",
    ),
    path(
        "bookinstance/<uuid:pk>/delete/",
        views.BookInstanceDelete.as_view(),
        name="bookinstance-delete",
    ),
]

from rest_framework.urlpatterns import format_suffix_patterns

# API URLs
api_urlpatterns = [
    path("api/authors/", views.AuthorList.as_view(), name="api-author-list"),
    path("api/authors/<int:pk>/", views.AuthorDetail.as_view(), name="api-author-detail"),
    path("api/genres/", views.GenreList.as_view(), name="api-genre-list"),
    path("api/genres/<int:pk>/", views.GenreDetail.as_view(), name="api-genre-detail"),
    path("api/languages/", views.LanguageList.as_view(), name="api-language-list"),
    path("api/languages/<int:pk>/", views.LanguageDetail.as_view(), name="api-language-detail"),
]

urlpatterns += format_suffix_patterns(api_urlpatterns)

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from catalog import views as catalog_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("", RedirectView.as_view(url="catalog/", permanent=True)),
]

urlpatterns += [
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register/", catalog_views.register, name="register"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
"""Models for  Local library"""

import uuid
from django.db import models
from django.urls import reverse
from django.db.models.functions import Lower
from django.conf import settings
from datetime import date


class Genre(models.Model):
    """Model representing a book genre"""

    name = models.CharField(
        max_length=200,
        help_text="Enter a book genre (e.g. Science fiction, fantasy, French poetry etc.)",
    )

    def __str__(self) -> str:
        return str(self.name)

    def get_absolute_url(self):
        """Returns the URL to access a particular genre instance"""
        return reverse("genre-detail", args=[str(self.pk)])

    class Meta:
        """Perform validations for valid genre name"""

        constraints = [
            models.UniqueConstraint(
                Lower("name"),
                name="genre_name_case_insensitive_unique",
                violation_error_message="Genre already exists (case-insensitive match)",
            )
        ]


class Book(models.Model):
    """Model representing a book (Not a specific copy of book)"""

    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        "Author", on_delete=models.RESTRICT, null=True, blank=True
    )
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book"
    )
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        unique=True,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
    )
    genre = models.ManyToManyField("Genre", help_text="Select the genre of this book")
    language = models.ForeignKey("Language", on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return str(self.title)

    def get_absolute_url(self):
        """Returns the URL access to a detail record for this boook"""

        return reverse("book-detail", args=[str(self.pk)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"


class BookInstance(models.Model):
    """Model representing a specific copy of a book"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this particular book across whole library",
    )
    book = models.ForeignKey(Book, on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ("m", "Maintenance "),
        ("o", "On loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text="Book availability",
    )

    borrower = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True
    )

    @property
    def is_overdue(self):
        """Verify whether due_back is empty and compare it with today's date"""
        return bool(self.due_back and date.today() > self.due_back)

    class Meta:
        ordering = ["-due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self) -> str:
        return f"{self.id} ({self.book.title})"
    
    def get_absolute_url(self):
        return reverse("bookinstance-detail", args=[str(self.pk)])


class Author(models.Model):
    """Model representing an author"""

    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(
        null=True, blank=True, help_text="The date should be of format YYYY-MM-DD"
    )
    date_of_death = models.DateField(
        "Died",
        null=True,
        blank=True,
        help_text="The date should be of format YYYY-MM-DD",
    )

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance"""
        return reverse("author-detail", args=[str(self.pk)])

    def __str__(self) -> str:
        return f"{self.last_name} {self.first_name}"


class Language(models.Model):
    """Model representing a language"""

    name = models.CharField(
        max_length=200,
        help_text="Enter the book's natural language (e.g. English, Malayalam, French)",
    )

    def __str__(self) -> str:
        return str(self.name)

    def get_absolute_url(self):
        """Returns the URL to access a particular language instance"""
        return reverse("language-detail", args=[str(self.pk)])

    class Meta:
        """Perform validations for valid language name"""

        constraints = [
            models.UniqueConstraint(
                Lower("name"),
                name="language_name_insesitive_unique",
                violation_error_message="Genre already exists (case-insensitive match)",
            )
        ]

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3)."
    )

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data<datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        
        return data

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
  <title>Local Library</title>
  {% endblock %}
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous" />

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <script src="{% static 'js/scripts.js' %}" defer></script>
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">

        {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'bookinstances' %}">All book copies</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>
          <li><a href="{% url 'genres' %}">All genres</a></li>
          <li><a href="{% url 'languages' %}">All languages</a></li>
        </ul>

        <ul class="sidebar-nav">
          {% if user.is_authenticated %}
          <li>User: {{ user.get_username }}</li>
          <li><a href="{% url 'my-borrowed' %}">My borrowed</a></li>
          <li>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-link">Logout</button>
            </form>
          </li>
          {% else %}
          {% if request.path != '/accounts/logout/' %}
          <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
          {% else %}
          <li><a href="{% url 'login'%}">Login</a></li>
          {% endif %}
          {% endif %}
        </ul>

        {% if user.is_staff %}
        <hr>
        <ul class="sidebar-nav">
          <li>Staff</li>
          <li><a href="{% url 'all-borrowed' %}">All borrowed</a></li>
          {% if perms.catalog.add_author %}
          <li><a href="{% url 'author-create' %}">Create author</a></li>
          {% endif %}
          {% if perms.catalog.add_genre %}
          <li><a href="{% url 'genre-create' %}">Create genre</a></li>
          {% endif %}
          {% if perms.catalog.add_language %}
          <li><a href="{% url 'language-create' %}">Create language</a></li>
          {% endif %}
          {% if perms.catalog.add_book %}
          <li><a href="{% url 'book-create' %}">Create book</a></li>
          {% endif %}
          {% if perms.catalog.add_bookinstance %}
          <li><a href="{% url 'bookinstance-create' %}">Create copy of book</a></li>
          {% endif %}
        </ul>
        {% endif %}

        {% endblock %}
      </div>

      <div class="col-sm-10">
        {% block content %}{% endblock %}

        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
          </span>
        </div>
        {% endif %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

catalog/templates/index.html
{% extends "base_generic.html" %} {% block content %}
<h1>Local Library Home</h1>
<p>Welcome to LocalLibrary</p>
<h2>Dynamic content</h2>
<p>The library has the following record counts:</p>
<ul>
  <li><strong>Books:</strong> {{ num_books }}</li>
  <li><strong>Copies:</strong> {{ num_instances }}</li>
  <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
  <li><strong>Authors:</strong> {{ num_authors }}</li>
</ul>

<p>
  You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
</p>
{% endblock %}